id: P445DF6CC
initial_creation_type: ocr
source_metadata:
  volumes:
    84a360571f29496a936e44d6389a2609:
      base_file: v116.txt
      image_group_id: I1PD95961
      title: རྒྱལ་པོ་ལ་གཏམ་བྱ་བ་རིན་པོ་ཆེའི་ཕྲེང་བ་ལས་བྱུང་བའི་སྨོན་ལམ་ཚིགས་སུ་བཅད་པ་ཉི་ཤུ་པ།
      total_pages: 1880
      volume_number: 116
